[package]
name = "effs-image"
version = "0.0.1"
edition = "2021"

[dependencies]
effs = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
